### ISSUE TITLE
Duplicate content in title, Crab - Crab

### ISSUE THREAD

**Issue by bozidarsevo** [thomasheller/crab#10]
In header.html partial there is {{ .Title }} - {{ .Site.Title }} but when you are on the home page .Title and .Site.Title are the same, and you get page title "Crab - Crab".

**Comment by drowssaPdnAemanresU** [comment]
Fixed in https://github.com/drowssaPdnAemanresU/crab and awaiting the pull request to be approved.

**Comment by thomasheller** [comment]
Actually, something else is going on here. The title of the home page is set to `Home`, therefore the title should render as `Home - Crab`. Any idea why Hugo behaves differently in the home page context?

**Comment by thomasheller** [comment]
The same is happening in the `h1` tag of `header.html` where Hugo renders `Crab` (the site title) instead of `Home` (the page title) for the home page.

**Comment by davidsneighbour** [comment]
How about `.Page.Title`?

**Comment by thomasheller** [comment]
`.Page.Title` renders the site title as well.

**Comment by thomasheller** [comment]
Also see this discussion: https://discourse.gohugo.io/t/how-to-use-page-title-in-homepage-context/18987

**Comment by thomasheller** [comment]
Solved per solution suggested there.
