### ISSUE TITLE
Problem displaying Blogs

### ISSUE THREAD

**Issue by rusher81572** [thomasheller/crab#11]
Hello, I am looking at moving a site at work to Hugo (Hugo Static Site Generator v0.36 darwin/amd64 BuildDate:) using this awesome theme on GitHub Pages. However, I ran into an issue showing the blog posts when I click on /blog.

When I have baseurl set to  ```baseurl = "/"```, I can see blog posts on /blog locally. the /blog/index.html is populated with the entries.

When set to ```baseurl = "https://rusher81572.github.io/seastar/"```, I do not see any blog posts on /blog. /blog/index.html is not populated with the entries.

Regardless of the baseurl, index.xml is populated correctly.

**Comment by rusher81572** [comment]
Looks like I was able to fix it by modifying _default/list.html as shown
```
{{ if hasPrefix .URL "/seastar/blog/" }}
```

**Comment by drowssaPdnAemanresU** [comment]
Fixed in https://github.com/drowssaPdnAemanresU/crab and awaiting the pull request to be approved.

**Comment by thomasheller** [comment]
I've tried to simplify this by 0cb1f08, so any baseURL should work. Please open a new issue if things still don't work as expected. Thanks!
