### ISSUE TITLE
Are you sure the 2nd column layout works ?

### ISSUE THREAD

**Issue by AndrewHobson** [thomasheller/crab#19]
Hello,

If you compare the screen shot of the Crabe layout
here : https://themes.gohugo.io/crab/

With the demo version 
here : https://themes.gohugo.io/theme/crab/

You can see that in the demo version, there is no 2nd column with the text : Summary: Crab is a clean Hugo theme for websites. Its features include responsiveness, nested menu support, two-column layout, tag and blog article support.

Is this a bug ?

Because I am unable to make the two-column layout work !

Thanks.

Andrew

**Comment by jmooring** [comment]
See https://discourse.gohugo.io/t/unable-to-make-crab-theme-multi-column-work/28175/2

**Comment by thomasheller** [comment]
Thank you @jmooring for helping out.

I updated the README and example site to be compatible with recent versions of Hugo.
