### ISSUE TITLE
Posts, tags and archive

### ISSUE THREAD

**Issue by nistara** [thomasheller/crab#2]
Hi, thank you for this great theme! I'm looking to transition from Jekyll to Hugo, and came across `crab` while searching for themes. Would it be possible to have a page for articles/posts, be able to assign (and view) tags, and an archive as well? Sorry if this is asking too much, but any insight or help would be appreciated. 

Thanks again :)

**Comment by thomasheller** [comment]
@nistara It looks like you're looking for a blog theme, while Crab was mainly designed as a theme for websites with fixed pages. I'm going to add some of the features you suggested though, because I believe the theme would benefit from being more versatile.

**Comment by nistara** [comment]
Great, thank you!

**Comment by thomasheller** [comment]
@nistara The current version has a few more features (regarding tags and blog posts), although there is still room for improvement. It could take up to a week for the changes to appear in the [Hugo theme showcase](http://themes.gohugo.io/), but you could clone the repository and run the example site locally, as described in the README.
