### ISSUE TITLE
It's more a question than an issue...

### ISSUE THREAD

**Issue by AndrewHobson** [thomasheller/crab#20]
On the demo page Contact : https://themes.gohugo.io//theme/crab/contact/

I'm not able to understand and reproduce the shortcode to put the address in Italic
Mister Crab
42 Ocean Street
Oceania, OC 98765

Can you explain how it works ?

Thanks !

**Comment by thomasheller** [comment]
Hello @AndrewHobson 

The italic address in the example site is actually not produced by a Hugo shortcode, it is achieved using simple Markdown formatting.

In this case, putting the address between asterisks (`*...*`) renders the enclosed text as emphasized, italic text.

You can find further information regarding the Markdown format here: https://gohugo.io/content-management/formats/#learn-markdown
